project:
  type: website

website:
  title: "Peace"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/amruthaajish17
      - icon: twitter
        href: https://twitter.com
      - icon: instagram
        href: https://www.instagram.com/i._.am_ruthaaa/
format:
  html:
    theme: quartz
    css: styles.css



